name: Black Formatting

on:
  pull_request:
    branches:
      - main
jobs:
  black:
    uses: ./.github/workflows/setup-python-poetry.yml
    with:
      python-version: "3.10"
    steps:
      - name: Run Black
        run: poetry run black --check .